### PR TITLE
Add password visibility

### PR DESCRIPTION
**Pull request by sbhat893**
In the login screen the 'show password' and 'hide password' is implemented.

### CODE REVIEW

**Comment by sbhat893** [comment]
screenshot_2018-04-25-05-06-59 1
screenshot_2018-04-25-05-07-09 1

**Comment by sbhat893** [comment]
screenshot_2018-04-25-05-55-18 1
screenshot_2018-04-25-05-55-26 1

**Comment by lucifer0987** [comment]
we are using firebase, so no need of this bro.. we are closing ur PR
But, don't worry... only raising PR counts.. it doesn't matter whether the Pr is accepted or not...
it will count towards ur progress..

**Comment by sbhat893** [comment]
Ok. I'll try my best in the project.

**Pull request closed without merging**
